add support for LZW compression
tlnagy/TiffImages.jl pull request #116
Opened 2023-09-27 00:49 UTC by chrstphrbrns

Fixes #8 

Validated using images from a variety of packages, using a variety of pixel formats, and comparing with uncompressed versions of the same image

2023-09-27 03:19 UTC, tlnagy commented
Wow, thanks! LZW support has been requested for awhile. 

I'll review this carefully later this week, but do you mind adding tests? I believe `bali.tif` from my tlnagy/exampletiffs repo is LZW compressed. 

Also is this your own original implementation or was this adapted from somewhere? We just need to make sure the licenses are compatible if the latter.

2023-09-27 12:17 UTC, chrstphrbrns commented
This implementation is not adapted or ported from any other code

2023-10-02 22:28 UTC, tlnagy commented on src/ifds.jl
> +end
Do you mind adding docs to `TiffFileStrip`?

2023-10-02 23:12 UTC, tlnagy commented
Do you mind bumping the version to `v0.7.0`?

2023-10-05 22:40 UTC, tlnagy requested changes

2023-10-05 23:20 UTC, chrstphrbrns commented on src/ifds.jl
> +struct TiffFileStrip{T}
`T` is the sample type, which is neither `O` nor `S`. It was added to address type instability in `reverse_prediction!`

2023-10-06 01:32 UTC, tlnagy commented on src/ifds.jl
> +struct TiffFileStrip{T}
Ah that makes sense. The 3 parameter type should do the trick, without it @code_warntype was complaining about `TiffFileStrip`.

2023-10-06 01:33 UTC, tlnagy approved these changes

2023-10-09 18:07 UTC, tlnagy commented
Okay, I think this is good to go. I'll tag v0.6.8 first to release #121 and then we'll tag and release this PR as v0.7.0

2023-10-10 18:04 UTC, merged

2023-10-10 18:06 UTC, tlnagy commented
Thanks @chrstphrbrns for pushing this all the way through! I think people will be very excited for this.