Use PermutedDimsArray during write
tlnagy/TiffImages.jl pull request #33
Opened 2021-02-22 04:31 UTC by IanButterworth

Gives a slight increase in write speed. Benchmarks over in https://github.com/JuliaIO/FileIO.jl/pull/290

2021-02-22 04:42 UTC, tlnagy commented
Huh. I guess eager evaluation is a negative here.

2021-02-22 05:41 UTC, IanButterworth commented
Turns out a lot of the slowness was julia's write handler unfolding the complex array type sent to write.
Doing a collect after the views greatly improves speed (this PR takes a 1000x1000 image from 70ms to 2ms)

2021-02-24 17:33 UTC, IanButterworth commented
@tlnagy Cache now set up, and performs well https://github.com/JuliaIO/FileIO.jl/pull/290#issuecomment-785246209

2021-02-24 19:21 UTC, tlnagy requested changes
Hi @IanButterworth, thanks for implementing the cache idea! I think it's unnecessary to build the write-cache on construction of the `DenseTaggedImage` type because many TIFFs will only be read and never written. I think it's better to construct this on write.

2021-02-24 19:21 UTC, tlnagy commented on src/types/dense.jl
> +    pagecache::Matrix{UInt8}
I'm not a fan of placing the write cache in the struct itself. I think it would be sufficient to construct this in the `write` function below.

2021-02-24 19:21 UTC, tlnagy commented on src/types/dense.jl
I would construct the cache here instead.

2021-02-24 20:11 UTC, IanButterworth commented
Good point! Moved the cache to write time.
Also set up the SnoopCompile tooling to auto-generate and install precomp statements. Results again over in https://github.com/JuliaIO/FileIO.jl/pull/290#issuecomment-785342346

2021-02-24 20:20 UTC, tlnagy approved these changes

2021-02-24 20:23 UTC, tlnagy commented
I think this looks good to be merged from my end!

I'm not sure if the snooping makes a difference in its current form, but perhaps that's because of latency higher up in the stack.

2021-02-24 20:56 UTC, tlnagy commented
Could we move the Snoopcompile stuff into a separate PR and I can go ahead and merge the cache-collect portion of this?

2021-02-24 21:00 UTC, IanButterworth commented
Yeah I agree

2021-02-24 21:30 UTC, IanButterworth commented
> move the Snoopcompile stuff into a separate PR

👍🏻 https://github.com/tlnagy/TiffImages.jl/pull/35

2021-02-24 21:36 UTC, merged

2021-02-24 21:36 UTC, tlnagy commented
Awesome, thanks for figuring this out!